version: '3.8'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
      - ./setup.sql:/tmp/setup.sql
    command: ./tmp/entrypoint.sh

  api:
    image: api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    networks:
      - library-network
    depends_on:
      - sqlserver
    restart: always
    ports:
      - 5023:8080
networks:
    library-network:
        driver: bridge
