version: '3.8'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always

  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
      - ./setup.sql:/tmp/setup.sql
    command: chamod +x ./tmp/entrypoint.sh && ./tmp/entrypoint.sh
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - library-network
 
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
    networks:
      - library-network
    depends_on:
      - sqlserver
    restart: always
    ports:
      - 5023:8080

  # tests:
  #   image: ${DOCKER_REGISTRY-}tests
  #   build:
  #     context: .
  #     dockerfile: tests/Tests/Dockerfile
  #   networks:
  #     - library-network
  #   depends_on:
  #     - sqlserver


networks:
    library-network:
        driver: bridge

  

